/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button/index.vue')['default']
    ListItem: typeof import('./components/List-Item/index.vue')['default']
    Selector: typeof import('./components/List-Item/Selector/index.vue')['default']
    Title: typeof import('./components/Title/index.vue')['default']
    VerticalLine: typeof import('./components/Vertical-Line/index.vue')['default']
  }
}
